### ISSUE TITLE
adding repo issue

### ISSUE THREAD

**Issue by mil1meter** [komikku-app/extensions#3]
I can't add the repo either manually or automatically. it says "invalid repo url".

**Comment by cuong-tran** [comment]
How do you add it?

Please go to this site: https://komikku-app.github.io/docs/guides/getting-started using your phone then press the button to add source.

**Comment by Blade694** [comment]
I also tried to add the repo both ways, by website and manually. Both ways it's showing "invalid repo url". I tried to replicate this on yokai/mihon, but this repo easily got added in them and didn't show this invalid repo url issue.

**Comment by cuong-tran** [comment]
> I also tried to add the repo both ways, by website and manually. Both ways it's showing "invalid repo url". I tried to replicate this on yokai/mihon, but this repo easily got added in them and didn't show this invalid repo url issue.

Which app do you want to add this repo in? I will try it myself.

In case you want to add this repo to Komikku app itself, it will fail since this repo is already included in the app. If it is the case, it will say invalid repo.

**Comment by Blade694** [comment]
> Which app do you want to add this repo in? I will try it myself.
> 
> In case you want to add this repo to Komikku app itself, it will fail since this repo is already included in the app. If it is the case, it will say invalid repo.

I tried to add this repo in komikku app itself where it said invalid repo url. According to what you said, this repo is already included in the app that's why it showed that issue. Although I'm unable to see it in extension repo category in the app.
And does that mean, we don't need to add keiyoushi extension repo in the app for the extensions to show up?
